Update shenzhen.json
railmapgen/rmg-palette pull request #32
Opened 2022-03-17 07:39 UTC by EupGH

添加6支
更改14，16，20颜色

2022-03-17 08:03 UTC, wongchito commented
你好@EupGH,

請問所修改顏色之來源為？我對比了Wikipedia的Template:深圳地鐵顏色頁面，發現所更新之顏色存在少許出入，以及6號線支線並無專用顏色。

2022-03-17 08:15 UTC, wongchito requested changes

2022-03-17 08:15 UTC, wongchito commented on public/resources/palettes/shenzhen.json
> +            "zh-Hant": "6號線支綫"
請統一使用「線」

2022-03-17 10:08 UTC, EupGH commented
> 你好@EupGH,
> 
> 請問所修改顏色之來源為？我對比了Wikipedia的Template:深圳地鐵顏色頁面，發現所更新之顏色存在少許出入，以及6號線支線並無專用顏色。

出入为从pantone转换为hex时产生的误差，我是在Illustrator上将色号转换的，因此与wiki出现了少量出入。
而6号线支线，截至目前官方虽然并没有给出具体的色号，但是在线路图中“意外泄漏”，可见[此处](http://www.ditiezu.com/forum.php?mod=viewthread&tid=738687)，我自己选择了较为接近图中色号的颜色，而待官方公布具体色号后再做修正。
“线”字的错误确属粗心。

2022-03-17 12:50 UTC, wongchito commented
了解。在閣下修改「線」字後，我將會merge閣下的PR

2022-03-26 17:12 UTC, wongchito commented
Covered in 273320bb

2022-03-26 17:12 UTC, closed without merging